Add missing include header for wxTextValidator
The use of wxTextValidator was introduced by upstream commit
4a313a303bb662a0823f344f64627c7b2ca0c743, but w/o the proper
include header, i.e. '#include <wx/valtext.h>'.

Error reported on Gentoo GNU/Linux amd64:

../aegisub-9999/src/dialog_dummy_video.cpp: In constructor ‘{anonymous}::DialogDummyVideo::DialogDummyVideo(wxWindow*)’:
../aegisub-9999/src/dialog_dummy_video.cpp:120:9: error: ‘wxTextValidator’ was not declared in this scope; did you mean ‘wxValidator’?
  120 |         wxTextValidator fpsVal(wxFILTER_INCLUDE_CHAR_LIST, &fps);
      |         ^~~~~~~~~~~~~~~
      |         wxValidator
../aegisub-9999/src/dialog_dummy_video.cpp:121:9: error: ‘fpsVal’ was not declared in this scope
  121 |         fpsVal.SetCharIncludes("0123456789./");
      |         ^~~~~~

References:
 - https://docs.wxwidgets.org/3.2.5/classwx_text_validator.html